/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parking;

import java.util.ArrayList;
import java.util.function.Predicate;
import javax.swing.JOptionPane;

/**
 *
 * @author tomasz
 */
public class ParkApp extends javax.swing.JFrame {
    private ParkApp parkApp;
    private boolean enableFlag = false;
    private ParkingArea area;
    private final ArrayList<String> data = new ArrayList<>();
    private int areaSize = 100;
    /**
     * Creates new form ParkApp
     */
    public ParkApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parkInit = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        sizeField = new javax.swing.JTextField();
        initButton = new javax.swing.JButton();
        feeConf = new javax.swing.JFrame();
        confCategory = new javax.swing.JComboBox<>();
        confTextField = new javax.swing.JTextField();
        confButton = new javax.swing.JButton();
        inPlate = new javax.swing.JTextField();
        outPlate = new javax.swing.JTextField();
        inButton = new javax.swing.JButton();
        outButton = new javax.swing.JButton();
        categoryCB = new javax.swing.JComboBox<>();
        fillBar = new javax.swing.JProgressBar();
        fillBarLabel = new javax.swing.JLabel();
        plateLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfVehicles = new javax.swing.JList<>();
        pvLabel = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        feeValue = new javax.swing.JLabel();
        feeCFG = new javax.swing.JButton();

        parkInit.setTitle("Initialize");
        parkInit.setAlwaysOnTop(true);
        parkInit.setMinimumSize(new java.awt.Dimension(170, 122));
        parkInit.setResizable(false);
        parkInit.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                parkInitWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                parkInitWindowClosed(evt);
            }
        });

        jLabel2.setText("Insert size of parking area");

        initButton.setText("OK");
        initButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parkInitLayout = new javax.swing.GroupLayout(parkInit.getContentPane());
        parkInit.getContentPane().setLayout(parkInitLayout);
        parkInitLayout.setHorizontalGroup(
            parkInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkInitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parkInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sizeField)
                    .addComponent(initButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parkInitLayout.setVerticalGroup(
            parkInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkInitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(initButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        feeConf.setTitle("Fee Configuration");
        feeConf.setMinimumSize(new java.awt.Dimension(187, 69));
        feeConf.setResizable(false);

        confCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        confCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confCategoryActionPerformed(evt);
            }
        });

        confButton.setText("OK");
        confButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout feeConfLayout = new javax.swing.GroupLayout(feeConf.getContentPane());
        feeConf.getContentPane().setLayout(feeConfLayout);
        feeConfLayout.setHorizontalGroup(
            feeConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feeConfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confButton, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );
        feeConfLayout.setVerticalGroup(
            feeConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feeConfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feeConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ParkApp");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        inButton.setText("IN");
        inButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inButtonActionPerformed(evt);
            }
        });

        outButton.setText("OUT");
        outButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outButtonActionPerformed(evt);
            }
        });

        categoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        categoryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryCBActionPerformed(evt);
            }
        });

        fillBar.setValue(100);

        fillBarLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fillBarLabel.setLabelFor(fillBar);
        fillBarLabel.setText("Fill level:");

        plateLabel.setText("Plate number");

        categoryLabel.setText("Category");

        listOfVehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listOfVehiclesMouseClicked(evt);
            }
        });
        listOfVehicles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listOfVehiclesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listOfVehicles);

        pvLabel.setText("Parked vehicles:");

        fee.setText("Fee:");

        feeValue.setText("0.00");

        feeCFG.setText("CHANGE FEE");
        feeCFG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeCFGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(outPlate, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(inPlate)
                            .addComponent(plateLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(categoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(fee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(feeValue)
                                .addGap(18, 18, 18)
                                .addComponent(outButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoryLabel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(feeCFG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pvLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fillBarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fillBar, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateLabel)
                    .addComponent(categoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(outPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fee)
                        .addComponent(feeValue)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(feeCFG)
                .addGap(14, 14, 14)
                .addComponent(pvLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fillBarLabel)
                    .addComponent(fillBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryCBActionPerformed

    private void inButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inButtonActionPerformed
        // TODO add your handling code here
        try{
            Vehicle v = new Vehicle(inPlate.getText(),categoryCB.getSelectedItem().toString());
            area.parkVehicle(v);
            data.add(v.toString());
            fillBar.setValue(100/areaSize*area.getFreeSpots());
            listOfVehicles.setListData(data.toArray(new String[0]));
        }
        catch(IndexOutOfBoundsException | IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally{
            inPlate.setText("");
        }
        
    }//GEN-LAST:event_inButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        parkInit.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outButtonActionPerformed
        // TODO add your handling code here:
        try{
            feeValue.setText(String.format("%.2f", area.exitArea(outPlate.getText())));
            Predicate<String> p = (x) -> x.split(" ")[0].equals(outPlate.getText());
            data.removeIf(p);
            listOfVehicles.setListData(data.toArray(new String[0]));
            fillBar.setValue(100/areaSize*area.getFreeSpots());
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally{
            outPlate.setText("");
        }
    }//GEN-LAST:event_outButtonActionPerformed

    private void listOfVehiclesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listOfVehiclesValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listOfVehiclesValueChanged

    private void listOfVehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listOfVehiclesMouseClicked
        // TODO add your handling code here:
        try{
        outPlate.setText(listOfVehicles.getSelectedValue().split(" ")[0]);
        }
        catch(NullPointerException e){}
    }//GEN-LAST:event_listOfVehiclesMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void initButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initButtonActionPerformed
        // TODO add your handling code here:
        try{
            setSize(Integer.parseInt(sizeField.getText()));
            area = new ParkingArea(areaSize);
            enableFlag = true;
            parkInit.setVisible(false);
        }
        catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, "Incorrect value");
        }
    }//GEN-LAST:event_initButtonActionPerformed

    private void parkInitWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_parkInitWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_parkInitWindowClosed

    private void parkInitWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_parkInitWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_parkInitWindowClosing

    private void feeCFGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeCFGActionPerformed
        // TODO add your handling code here:
        feeConf.setVisible(true);
    }//GEN-LAST:event_feeCFGActionPerformed

    private void confCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confCategoryActionPerformed
        // TODO add your handling code here:
        confTextField.setText(String.valueOf(area.getFee(confCategory.getSelectedItem().toString())));
    }//GEN-LAST:event_confCategoryActionPerformed

    private void confButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confButtonActionPerformed
        // TODO add your handling code here:
        try{
            area.setFee(confCategory.getSelectedItem().toString(), Float.parseFloat(confTextField.getText()));
            JOptionPane.showMessageDialog(null, "Value changed");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Wrong value");
        }
    }//GEN-LAST:event_confButtonActionPerformed

    private void setSize(int size){
        if(size>0)
            areaSize = size;
        else
            throw new IllegalArgumentException("Negative value");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ParkApp parkApp = new ParkApp();
                parkApp.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryCB;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton confButton;
    private javax.swing.JComboBox<String> confCategory;
    private javax.swing.JTextField confTextField;
    private javax.swing.JLabel fee;
    private javax.swing.JButton feeCFG;
    private javax.swing.JFrame feeConf;
    private javax.swing.JLabel feeValue;
    private javax.swing.JProgressBar fillBar;
    private javax.swing.JLabel fillBarLabel;
    private javax.swing.JButton inButton;
    private javax.swing.JTextField inPlate;
    private javax.swing.JButton initButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOfVehicles;
    private javax.swing.JButton outButton;
    private javax.swing.JTextField outPlate;
    private javax.swing.JDialog parkInit;
    private javax.swing.JLabel plateLabel;
    private javax.swing.JLabel pvLabel;
    private javax.swing.JTextField sizeField;
    // End of variables declaration//GEN-END:variables
}
